### ISSUE TITLE
license

### ISSUE THREAD

**Issue by IzzySoft** [petabyt/fujiapp#3]
Great you're making the app publicly available open-source! Digging in the code I see it's put under GPL-2.0 :heart_eyes: Could you please add the `LICENSE` file to the repo root to make that more obvious (so one hasn't to dig in the code to find out)? Thanks in advance!

**Comment by IzzySoft** [comment]
PS: it seems like all the current APKs identify with the same version:

    package: name='dev.danielc.fujiapp' versionCode='1' versionName='0.1.0-beta'

Could you please make them "unique"? For example, the currently latest tag is named `0.0.4` and is the 4th "release". It would be expected to have `versionName: "0.0.4"` and `versionCode >= 4`.

* `versionName`: this is what the person using your app will see. So when asked what version is installed (e.g. with a bug report), this would help.
* `versionCode`: this is what Android uses internally to tell versions apart – and to decide whether an APK is an update to the installed version or not. So this will help to propagate updates.

**Comment by petabyt** [comment]
> Could you please add the LICENSE file to the repo root to make that more obvious

Yes, I've been meaning to do this for a while, will do

> Could you please make them "unique"?

The current releases I've been throwing on Github aren't stable or complete (hence the `-beta`), most of them only have a bug fix or two. I'm sending out the APK link to people who can test it and return the debug info. The version code and name will be incremented when a few release is put on Google Play (which should be soon, once I get a few bugs fixed)

**Comment by IzzySoft** [comment]
Thanks! So Google Play is still a thing? :see_no_evil: Actually, I broke all ties to that one years ago. Maybe you'd also be interested to have your FOSS app listed in FOSS places? There's [F-Droid.org](https://f-droid.org/) for when your app is "ready for the masses". FOSS & Privacy folks trust that place. Until then, there are third-party repos to be used with F-Droid clients – like mine, which is surprisingly well-known meanwhile (imagine my surprise when I tested a youtube client app, using "fdroid" as search term, and the first thing coming up was a video someone made about my repo…

Such listings help to keep the app updated on-device more or less automatically. I took the freedom to prepare a place for you [here](https://apt.izzysoft.de/packages/dev.danielc.fujiapp/), hope you like it…

**Comment by petabyt** [comment]
Thanks! I remember putting an app on f-droid a long time ago. I remember the review and submission process being difficult, I'll consider adding it if it's easy.

**Comment by IzzySoft** [comment]
And I remember your "nick" (Github user name) but could not put it to any app in my repo. Now it's clear why (disclosure: I'm also one of the maintainers at F-Droid). I'll gladly assist you with the listing when the time comes!

**Comment by petabyt** [comment]
> And I remember your "nick" (Github user name) but could not put it to any app in my repo. Now it's clear why (disclosure: I'm also one of the maintainers at F-Droid). I'll gladly assist you with the listing when the time comes!

Oh yeah, I did the Bible app with you: https://gitlab.com/fdroid/rfp/-/issues/1040#note_198414271

**Comment by IzzySoft** [comment]
Ah, yes! Thanks for solving the riddle for me :smiley:

**Comment by IzzySoft** [comment]
@petabyt the latest APK (0.0.5-pre) still identifies the same as all previous ones:

    package: name='dev.danielc.fujiapp' versionCode='1' versionName='0.1.0-beta'

If you could fix that, I could add your app to my repo :smiley:

**Comment by petabyt** [comment]
Right now it's just a test release so I'm not ready to publish yet. I'll change it when I do a stable-ish release, which should be soon.

**Comment by IzzySoft** [comment]
Ah, OK – fair enough. Can you drop me a note then to pick it up? Like, a comment here?

**Comment by petabyt** [comment]
> Ah, OK – fair enough. Can you drop me a note then to pick it up? Like, a comment here?

Sure. Or maybe you can click the watch button and select releases only?

**Comment by IzzySoft** [comment]
I'd prefer it the other way. Subscriptions tend to be forgotten, and suddenly you wonder where all those mails come from…

**Comment by petabyt** [comment]
Izzy thanks for helping put Fudge on fdroid!
Is there a process to update the metadata for the store listing? I'd like to have the icon and description changed. (And I have a new release ready soon)

**Comment by IzzySoft** [comment]
Yupp. It's called "Fastlane" and lets you have all those metadata (description, graphics) in your repo here so you can maintain them yourself. With each new release, they are pulled along then. See my [Fastlane Cheat Sheet](https://gitlab.com/-/snippets/1895688) for details and guidance.

Btw: you don't need the Fastlane binaries for that. F-Droid as well as my repo just need those text and graphic files in the described places. Even an "incomplete set" helps already, so you don't need to establish everything at once. You could e.g. start with the short and full description plus the icon, then later add some screenshots, at some point a featureGraphic (or not), and so on.

If you want, I can send you a PR with what is currently set up in my repo, so you can build on that. Just let me know, and I'll open the proper PR.
