### ISSUE TITLE
Does't work with a XT5

### ISSUE THREAD

**Issue by Morglaf** [petabyt/fujiapp#5]
If I Can help... But I am not a developer...
Thank for the work

**Comment by petabyt** [comment]
A screenshot and log file would help

**Comment by Morglaf** [comment]
Maybe I'm stupid, but the device needs a bluetooth connection to initiate the wifi connection...
![Screenshot_2023-07-17-11-26-27-494_dev danielc fujiapp](https://github.com/petabyt/fujiapp/assets/22679426/e3f0bb77-fab3-4e6b-94d9-8dd1ce7be51e)
